# Useful resource: https://github.com/actions/starter-workflows

name: Jest Tests

on:
  # https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requestpaths
  # More helpful: https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events
  push:
    branches:
      # If this isn't defined then all PR tests will be run twice
      - master
    paths:
      - '*'
      - '!*.md'
      - .github/workflows/Jest.yml
  pull_request:
    paths:
      - '*'
      - '!*.md'
      - .github/workflows/Jest.yml

jobs:
  test:
    name: Jest Tests
    strategy:
      matrix:
        # Run tests with all of these node versions/systems :]
        # node-version: [8.x, 10.x, 12.x]
        node-version: [10.x]
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node Dependencies
        run: |
          npm install && npm run test
        env:
          CI: true
      # - name: Run Tests
      #   uses: rkusa/jest-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
