name: Unit Tests

on: [push]

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: [8.x, 10.x, 12.x]
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node Dependencies
        run: |
          npm install
        env:
          CI: true
      - name: Run Tests
        uses: rkusa/jest-action:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
